authors: 
  - Fernando Quinonez <fernando.andres.quinonez.granados@gmail.com> 
  - Antonio Goez <antoniogoez@gmail.com>
homepage: https://github.com/quinonez/BBT-Dart
name: bbt
version: 1.0.7
description: Building Blocks and Tools (BBT) CLI Library. For Scientists, Engineers, Educators and Students.
dependencies: 
  args: any
  dart_style: any
  test: any

